name: fitopia2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0 
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  json_annotation: ^4.9.0
  yaml: ^3.0.0
  provider: ^6.1.2          # ✅ AI ViewModel için önerilen state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/alev5.webp
   - assets/images/fitopia.jpg
   - assets/images/background.png
   - assets/images/eller.jpg
   - assets/images/background.jpg 
   - assets/images/koşu5.webp
   - assets/images/su.webp
   - assets/images/nutrition.jpg
   - assets/images/nutrition2.jpg
   - assets/images/nutrition3.jpg
   - assets/images/exercise.jpg
   - assets/images/dinner.jpg
   - assets/images/yesil9.png
   - assets/images/breakfast.jpg
   - assets/images/lunch.jpg
   - assets/images/snack.jpg
   - .env                    # ✅ Gemini API anahtarını buradan okuyacağız

  fonts:
    - family: SourceSerif
      fonts:
        - asset: assets/fonts/SourceSerif.ttf
    - family: Courgette-Regular
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
        - asset: assets/fonts/username.otf
