// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBI7lv31xIZUJcUkwodUkOO4RKfzxFwE',
    appId: '1:366171316416:web:b9967c19d98267468e4d25',
    messagingSenderId: '366171316416',
    projectId: 'fitopia-crew',
    authDomain: 'fitopia-crew.firebaseapp.com',
    storageBucket: 'fitopia-crew.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Aua-z_oKeVa_FQPF_2UWc6Nlg2o_X94',
    appId: '1:366171316416:android:93a31d5c753856e58e4d25',
    messagingSenderId: '366171316416',
    projectId: 'fitopia-crew',
    storageBucket: 'fitopia-crew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5HzFyvPJxIMhLM3BPpQTwn9QKhCyxjZE',
    appId: '1:366171316416:ios:006eb8ae6e5ef0298e4d25',
    messagingSenderId: '366171316416',
    projectId: 'fitopia-crew',
    storageBucket: 'fitopia-crew.firebasestorage.app',
    iosBundleId: 'com.example.fitopia2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5HzFyvPJxIMhLM3BPpQTwn9QKhCyxjZE',
    appId: '1:366171316416:ios:006eb8ae6e5ef0298e4d25',
    messagingSenderId: '366171316416',
    projectId: 'fitopia-crew',
    storageBucket: 'fitopia-crew.firebasestorage.app',
    iosBundleId: 'com.example.fitopia2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApBI7lv31xIZUJcUkwodUkOO4RKfzxFwE',
    appId: '1:366171316416:web:c668fd2e219778258e4d25',
    messagingSenderId: '366171316416',
    projectId: 'fitopia-crew',
    authDomain: 'fitopia-crew.firebaseapp.com',
    storageBucket: 'fitopia-crew.firebasestorage.app',
  );
}
