// ignore_for_file: use_key_in_widget_constructors

import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Iphone1611()])),
    );
  }
}

class Iphone1611 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Opacity(
                  opacity: 0.05,
                  child: Container(
                    width: 393,
                    height: 81,
                    decoration: ShapeDecoration(
                      color: const Color(0xFF902C2F),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 517,
                child: Opacity(
                  opacity: 0.30,
                  child: Container(
                    width: 393,
                    height: 180,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFFBB7B2),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 123,
                child: Container(
                  width: 223,
                  height: 223,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFCED2DE),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 116,
                top: 31,
                child: SizedBox(
                  width: 158,
                  height: 19,
                  child: Text(
                    'Egzersiz Planım',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 21,
                      fontFamily: 'Source Serif Pro',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 113,
                top: 151,
                child: Container(
                  width: 167,
                  height: 167,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/167x167"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 118,
                top: 547,
                child: SizedBox(
                  width: 158,
                  height: 25,
                  child: Text(
                    'Overhead Press',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 21,
                      fontFamily: 'Source Serif Pro',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 102,
                top: 577,
                child: SizedBox(
                  width: 189,
                  height: 33,
                  child: Text(
                    '16-20 kcal',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 21,
                      fontFamily: 'Source Serif Pro',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 123,
                child: Container(
                  width: 223,
                  height: 223,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF902C2F),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 283,
                top: 177,
                child: Container(
                  width: 18,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF902C2F),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 74,
                top: 368,
                child: SizedBox(
                  width: 246,
                  height: 60,
                  child: Text(
                    '0 : 55 : 42',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF902C2F),
                      fontSize: 30,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 115,
                top: 447,
                child: Container(
                  width: 163,
                  height: 39,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF902C2F),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 118,
                top: 416,
                child: Container(
                  width: 158,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF902C2F),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 141,
                top: 456,
                child: SizedBox(
                  width: 78,
                  height: 15,
                  child: Text(
                    'Duraklat',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 18,
                      fontFamily: 'Source Serif Pro',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 227,
                top: 453,
                child: Container(
                  width: 31,
                  height: 27,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 43,
                top: 629,
                child: SizedBox(
                  width: 322,
                  height: 33,
                  child: Text(
                    'Bu egzersiz omuz kasları, kol kasları, bacak bel ve karın kaslarınızı çalıştırmaktadır.',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Source Serif Pro',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 36,
                top: 658,
                child: SizedBox(
                  width: 317,
                  height: 36,
                  child: Text(
                    'Overhead Press, daha büyük kollara sahip güçlü, kaslı ve sağlıklı omuzlar inşa etmek için en iyi egzersizlerden biridir.',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Source Serif Pro',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
